version: '3.9'
services:
    nginx:
        image: nginx
        container_name: jjc_nginx
        restart: always
        depends_on:
            - php
            - postgres
        volumes:
            - "./conf/nginx/:/etc/nginx/conf.d/"
            - "./data/html/:/var/www/html/"
        ports:
            - 80:80
            - 443:443
    php:
        build: ./build/php-fpm
        container_name: jjc_php
        restart: always
        volumes:
            - "./conf/php/:/usr/local/etc/php/conf.d/"
            - "./data/html/:/var/www/html/"
            
    python:
        build: ./build/python
        container_name: jjc_python
        restart: always
        depends_on:
            - postgres
        ports:
            - 35946:35946
            
    postgres:
        image: postgres:12
        container_name: jjc_postgres
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - "./data/db/:/var/lib/postgresql/data"
            - "./conf/postgres/:/docker-entrypoint-initdb.d/"
        ports:
            - 5432:5432